name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build plugin using esbuild
        run: npm run build

      - name: Copy build files to temporary folder
        run: |
          mkdir build_output
          cp main.js main.js.map build_output/

      - name: Commit build artifacts to build branch and main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # === Update build branch ===
          # Start from main so that all required plugin files (like manifest.json) are present.
          git checkout main
          # Ensure build branch is created/updated off main.
          git checkout -B build
          # Overwrite/update build artifacts.
          cp -R build_output/* .
          git add -f main.js main.js.map
          git commit -m "Update build artifacts [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Wenlin88/Obsidian-API-Gateway.git build

          # === Update main branch as well ===
          git checkout main
          cp -R build_output/* .
          git add -f main.js main.js.map
          # Here we intentionally do not add a [skip ci] marker so that there’s a chance for Semantic Release 
          # to detect conventional commits if they exist. However, if your commit message should not trigger a release,
          # you may add [skip ci] only when appropriate.
          git commit -m "Update build artifacts" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Wenlin88/Obsidian-API-Gateway.git main

  release:
    if: github.ref == 'refs/heads/main'
    needs: build-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Automated Version Bump and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release