name: Build, Bump Version, and Upload Release Assets

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin using esbuild
        run: npm run build

      - name: List build output
        run: ls -al

      - name: Automated Version Bump and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release || echo "No releasable commits"

      - name: Get Latest Tag
        id: get_tag
        run: |
          # Fetch tags in case semantic-release just created one
          git fetch --tags
          echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"
      
      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Use the latest tag as created by semantic-release
          tag: ${{ steps.get_tag.outputs.tag }}
          files: |
            main.js
            manifest.json